name: Update Manifest

on:
  release:
    types: [published, deleted]

permissions:
  contents: write

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Generate manifest.json and deploy to gh-pages
        uses: Kevinjil/jellyfin-plugin-repo-action@v0.4.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pagesBranch: 'gh-pages'
